-- Add insights and peer_insights JSONB columns to session_mappings table
-- insights: Session insights generated by Gemini (at-a-glance, impressive things, issues, improvements)
-- peer_insights: Peer insights fetched from backend API for this session's journey node

ALTER TABLE "session_mappings" ADD COLUMN IF NOT EXISTS "insights" jsonb;
ALTER TABLE "session_mappings" ADD COLUMN IF NOT EXISTS "peer_insights" jsonb;
