openapi: 3.0.0
info:
  title: Profile View API
  version: 1.0.0
  description: API endpoints for the Timeline Journey Profile View feature

paths:
  /api/v2/timeline/nodes:
    get:
      summary: Get timeline nodes for current user or specified user
      description: Returns all timeline nodes for the authenticated user or a specified user
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
          description: Optional username to retrieve nodes for (requires appropriate permissions)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v2/timeline/nodes/{nodeId}:
    get:
      summary: Get detailed node information
      description: Returns comprehensive details about a specific timeline node
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the node to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeDetailsResponse'
        '404':
          description: Node not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - No permission to view node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ProfileResponse:
      type: object
      required:
        - profile
        - timeline
        - permissions
      properties:
        profile:
          type: object
          required:
            - userName
            - firstName
            - lastName
            - profileUrl
          properties:
            userName:
              type: string
              example: 'johndoe'
            firstName:
              type: string
              example: 'John'
            lastName:
              type: string
              example: 'Doe'
            profileUrl:
              type: string
              format: uri
              example: 'https://app.lighthouse.ai/johndoe'
        timeline:
          type: object
          required:
            - current
            - past
            - totalCount
          properties:
            current:
              type: array
              items:
                $ref: '#/components/schemas/TimelineNode'
            past:
              type: array
              items:
                $ref: '#/components/schemas/TimelineNode'
            totalCount:
              type: integer
              example: 42
        permissions:
          type: object
          required:
            - canEdit
            - canShare
          properties:
            canEdit:
              type: boolean
              example: true
            canShare:
              type: boolean
              example: true

    TimelineNode:
      type: object
      required:
        - id
        - type
        - userId
        - meta
        - createdAt
        - updatedAt
        - isCurrent
        - depth
        - permissions
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [job, education, project, event, action, careerTransition]
        parentId:
          type: string
          format: uuid
          nullable: true
        userId:
          type: integer
        meta:
          type: object
          properties:
            title:
              type: string
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
              nullable: true
            description:
              type: string
            # Additional type-specific fields
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        isCurrent:
          type: boolean
        depth:
          type: integer
        children:
          type: array
          items:
            $ref: '#/components/schemas/TimelineNode'
        permissions:
          $ref: '#/components/schemas/NodePermissions'

    NodeDetailsResponse:
      type: object
      required:
        - node
        - permissions
      properties:
        node:
          $ref: '#/components/schemas/TimelineNode'
        insights:
          type: array
          items:
            $ref: '#/components/schemas/NodeInsight'
        skills:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              category:
                type: string
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              url:
                type: string
        permissions:
          $ref: '#/components/schemas/NodePermissions'

    NodePermissions:
      type: object
      properties:
        canView:
          type: boolean
        canEdit:
          type: boolean
        canDelete:
          type: boolean
        canShare:
          type: boolean

    NodeInsight:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
